# Generated by Django 3.0.3 on 2020-02-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200227_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code_number',
            new_name='numcode',
        ),
    ]
