# Generated by Django 3.0.3 on 2020-02-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200227_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='numcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
