# Generated by Django 3.0.3 on 2020-03-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200227_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Ex: Sintia', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='Ex: +62xxxxxxxxxx', max_length=20),
        ),
    ]
