# Generated by Django 3.0.3 on 2020-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20200308_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_init',
            field=models.BooleanField(default=True),
        ),
    ]
