# Generated by Django 3.0.3 on 2020-03-18 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_auto_20200318_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='is_publish',
        ),
    ]
