# Generated by Django 3.0.3 on 2020-02-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemout',
            name='stockout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockoutitemout',
                                    to='stocks.StockOut'),
        ),
    ]
