# Generated by Django 3.0.3 on 2020-03-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20200308_1505'),
        ('stocks', '0002_auto_20200229_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='supplierstockin', to='users.Supplier'),
        ),
    ]
