# Generated by Django 3.0.3 on 2020-03-13 11:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0003_auto_20200313_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 13), null=True),
        ),
    ]
