# Generated by Django 3.0.3 on 2020-03-14 09:28

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0010_auto_20200313_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 14), null=True),
        ),
    ]
