# Generated by Django 3.0.3 on 2020-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0011_auto_20200314_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcard',
            name='is_init',
            field=models.BooleanField(default=True),
        ),
    ]
