# Generated by Django 3.0.3 on 2020-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0012_stockcard_is_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='is_init',
            field=models.BooleanField(default=True),
        ),
    ]
