# Generated by Django 3.0.3 on 2020-03-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0013_stockin_is_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemin',
            name='is_init',
            field=models.BooleanField(default=True),
        ),
    ]
