# Generated by Django 3.0.3 on 2020-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0014_itemin_is_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemin',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
