# Generated by Django 3.0.3 on 2020-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0015_auto_20200314_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='is_calculate',
            field=models.BooleanField(default=False),
        ),
    ]
