# Generated by Django 3.0.3 on 2020-03-20 18:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0017_auto_20200318_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='is_publish',
        ),
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 20), null=True),
        ),
    ]
