# Generated by Django 3.0.3 on 2020-03-22 22:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0020_remove_stockin_is_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 22), null=True),
        ),
    ]
