# Generated by Django 3.0.3 on 2020-03-25 07:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0022_auto_20200323_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcard',
            name='numcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 25), null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 25), null=True),
        ),
    ]
