# Generated by Django 3.0.3 on 2020-03-29 14:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0024_auto_20200327_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 29), null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 29), null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='is_init',
            field=models.BooleanField(default=True),
        ),
    ]
