# Generated by Django 3.0.3 on 2020-03-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_remove_product_is_publish'),
        ('users', '0010_remove_supplier_is_publish'),
        ('stocks', '0026_itemout_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemin',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemin',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='productitemin', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='itemin',
            name='stockin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='stockinitemin', to='stocks.StockIn'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='supplierstockin', to='users.Supplier'),
        ),
    ]
