# Generated by Django 3.0.3 on 2020-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0027_auto_20200329_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemin',
            name='end_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemout',
            name='end_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
