# Generated by Django 3.0.3 on 2020-04-01 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_auto_20200330_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 1), null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 1), null=True),
        ),
    ]
