# Generated by Django 3.0.3 on 2020-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_auto_20200406_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemout',
            name='end_stock',
            field=models.IntegerField(default=0),
        ),
    ]
