# Generated by Django 3.0.3 on 2020-03-18 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_auto_20200318_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_publish',
        ),
    ]
